#!/usr/bin/env bash
#
# Reads ../.env at the repo root and emits two artifacts under ios/Generated/:
#
#   1. Secrets.xcconfig — exposes each KEY as an Xcode build setting so it can
#      be referenced in plists with $(SPLIT_OAUTH_WEB_CLIENT_ID) etc.
#   2. Secrets.swift — generated Swift constants the keyboard / host app code
#      can import directly (e.g., `Secrets.oauthWebClientId`).
#
# Wire this into Xcode as a Run Script Build Phase that runs BEFORE "Compile
# Sources" on both targets:
#
#     "${SRCROOT}/Scripts/load-env.sh"
#
# Set "Input Files" → $(SRCROOT)/../.env so Xcode reruns when secrets change.
# Set "Output Files" → $(SRCROOT)/Generated/Secrets.swift to avoid redundant runs.
#
# The schema is defined in ../.env.example (committed). Add new keys there + here
# in the KEYS array below; the rest is automatic.

set -euo pipefail

# Repo root is two levels up from this script (ios/Scripts/).
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
ENV_FILE="$ROOT/.env"
OUT_DIR="$ROOT/ios/Generated"

# Keys we expose. Order doesn't matter; values are looked up by name.
KEYS=(
  "SPLIT_OAUTH_WEB_CLIENT_ID"
  "SPLIT_OAUTH_IOS_CLIENT_ID"
  "NOTION_OAUTH_CLIENT_ID"
  "NOTION_OAUTH_CLIENT_SECRET"
  "NOTION_OAUTH_REDIRECT_URI"
  "SLACK_OAUTH_CLIENT_ID"
  "SLACK_OAUTH_CLIENT_SECRET"
  "SLACK_OAUTH_REDIRECT_URI"
)

mkdir -p "$OUT_DIR"

# Read a key from .env (or empty if the file or key is missing).
read_env() {
  local key="$1"
  [ -f "$ENV_FILE" ] || { echo ""; return; }
  awk -F= -v k="$key" '
    $0 !~ /^[[:space:]]*#/ && $0 !~ /^[[:space:]]*$/ {
      gsub(/^[[:space:]]+|[[:space:]]+$/, "", $1)
      if ($1 == k) {
        sub(/^[^=]*=/, "")
        gsub(/^[[:space:]]+|[[:space:]]+$/, "")
        print
        exit
      }
    }
  ' "$ENV_FILE"
}

# -- Secrets.xcconfig -----------------------------------------------------------
XCCONFIG="$OUT_DIR/Secrets.xcconfig"
{
  echo "// AUTO-GENERATED by ios/Scripts/load-env.sh — do not edit."
  echo "// Source: $ENV_FILE"
  for k in "${KEYS[@]}"; do
    v="$(read_env "$k")"
    echo "$k = $v"
  done
} > "$XCCONFIG"

# -- Secrets.swift --------------------------------------------------------------
SWIFT="$OUT_DIR/Secrets.swift"
{
  echo "// AUTO-GENERATED by ios/Scripts/load-env.sh — do not edit."
  echo "// Source: $ENV_FILE"
  echo ""
  echo "import Foundation"
  echo ""
  echo "enum Secrets {"
  for k in "${KEYS[@]}"; do
    v="$(read_env "$k")"
    # Camel-case the constant name: SPLIT_OAUTH_WEB_CLIENT_ID -> splitOauthWebClientId
    name="$(echo "$k" | awk '{
      n = split(tolower($0), parts, "_")
      out = parts[1]
      for (i = 2; i <= n; i++) out = out toupper(substr(parts[i],1,1)) substr(parts[i],2)
      print out
    }')"
    # Escape backslashes + quotes for Swift string literal.
    escaped="${v//\\/\\\\}"
    escaped="${escaped//\"/\\\"}"
    echo "    static let ${name}: String = \"${escaped}\""
  done
  echo "}"
} > "$SWIFT"

echo "load-env.sh: wrote $XCCONFIG and $SWIFT"
