package com.prince.turtlekeyboard.emoji;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;

/**
 * Hand-curated keyword catalog backing the emoji panel's search field. Each
 * entry maps an emoji glyph to a small set of search terms — base name plus a
 * few common synonyms (e.g. "happy", "smile", "grin" for 😀). Coverage favours
 * the emojis users actually search for; less-common glyphs in
 * {@link EmojiData} are intentionally unindexed and still reachable by
 * category browsing.
 *
 * <p>Ranking: exact-keyword matches first, then prefix matches, then substring
 * matches, preserving insertion order within each tier.
 */
public final class EmojiSearchIndex {

    private static final Map<String, String[]> INDEX = new LinkedHashMap<>();

    static {
        // ── Smileys & faces ──
        add("😀", "grin", "smile", "happy", "face");
        add("😃", "smile", "happy", "grin", "joy");
        add("😄", "smile", "happy", "laugh");
        add("😁", "beam", "grin", "smile", "happy");
        add("😆", "laugh", "haha", "lol");
        add("😅", "sweat", "laugh", "nervous");
        add("🤣", "rofl", "laugh", "lol", "rolling");
        add("😂", "tears", "joy", "laugh", "cry", "lol");
        add("🙂", "slight", "smile");
        add("🙃", "upside", "down", "silly");
        add("😉", "wink");
        add("😊", "blush", "smile", "happy");
        add("😇", "angel", "innocent", "halo");
        add("🥰", "love", "hearts", "smile", "adore");
        add("😍", "love", "hearts", "eyes", "crush");
        add("🤩", "star", "struck", "wow");
        add("😘", "kiss", "blow");
        add("😗", "kiss");
        add("😙", "kiss", "smile");
        add("😚", "kiss", "closed");
        add("🥲", "tear", "smile", "bittersweet");
        add("😋", "yum", "savoring", "tongue", "delicious");
        add("😛", "tongue", "playful");
        add("😜", "wink", "tongue", "playful");
        add("🤪", "zany", "crazy", "silly", "goofy");
        add("😝", "tongue", "squint");
        add("🤑", "money", "rich", "dollar");
        add("🤗", "hug", "hugging");
        add("🤭", "oops", "giggle", "shy");
        add("🤫", "shush", "quiet", "secret");
        add("🤔", "think", "thinking", "hmm");
        add("🤐", "zip", "mouth", "secret");
        add("🤨", "raised", "eyebrow", "suspicious");
        add("😐", "neutral", "face", "meh");
        add("😑", "expressionless", "blank");
        add("😶", "no", "mouth", "silent");
        add("😏", "smirk", "smug");
        add("😒", "unamused", "meh");
        add("🙄", "eye", "roll", "annoyed");
        add("😬", "grimace", "awkward");
        add("🤥", "lie", "pinocchio");
        add("😌", "relieved", "calm");
        add("😔", "pensive", "sad", "down");
        add("😪", "sleepy", "tired");
        add("🤤", "drool", "tasty");
        add("😴", "sleep", "zzz", "tired");
        add("😷", "mask", "sick", "ill");
        add("🤒", "thermometer", "sick", "fever");
        add("🤕", "bandage", "hurt", "injured");
        add("🤢", "nausea", "sick", "yuck");
        add("🤮", "vomit", "puke", "sick");
        add("🤧", "sneeze", "sick", "cold");
        add("🥵", "hot", "sweat", "heat");
        add("🥶", "cold", "freezing", "ice");
        add("🥴", "woozy", "drunk", "dizzy");
        add("😵", "dizzy", "ko", "knocked");
        add("🤯", "mind", "blown", "exploding");
        add("🤠", "cowboy", "hat", "yeehaw");
        add("🥳", "party", "celebrate", "birthday");
        add("🥸", "disguise", "fake", "glasses");
        add("😎", "cool", "sunglasses", "shades");
        add("🤓", "nerd", "geek", "glasses");
        add("🧐", "monocle", "fancy", "examine");
        add("😕", "confused");
        add("😟", "worried");
        add("🙁", "frown", "sad");
        add("☹️", "frown", "sad");
        add("😮", "wow", "surprised", "open", "mouth");
        add("😯", "hushed", "surprised");
        add("😲", "astonished", "shock");
        add("😳", "flushed", "embarrassed");
        add("🥺", "pleading", "puppy", "eyes", "beg");
        add("😦", "frown", "open", "mouth");
        add("😧", "anguished");
        add("😨", "fear", "scared", "fearful");
        add("😰", "anxious", "sweat", "worried");
        add("😥", "sad", "relieved");
        add("😢", "cry", "tear", "sad");
        add("😭", "sob", "cry", "loud", "sad");
        add("😱", "scream", "fear", "shock");
        add("😖", "confounded");
        add("😣", "persevere", "struggle");
        add("😞", "disappointed", "sad");
        add("😓", "sweat", "tired");
        add("😩", "weary", "exhausted");
        add("😫", "tired", "exhausted");
        add("🥱", "yawn", "bored", "tired");
        add("😤", "huff", "frustrated", "steam");
        add("😡", "angry", "mad", "rage");
        add("😠", "angry", "mad");
        add("🤬", "swear", "cursing", "angry");
        add("😈", "devil", "imp", "evil");
        add("👿", "devil", "angry", "imp");
        add("💀", "skull", "dead", "death");
        add("☠️", "skull", "crossbones", "danger");
        add("💩", "poop", "poo", "shit");
        add("🤡", "clown", "creepy");
        add("👹", "ogre", "monster");
        add("👺", "goblin", "monster");
        add("👻", "ghost", "boo", "halloween");
        add("👽", "alien", "ufo");
        add("👾", "alien", "monster", "game");
        add("🤖", "robot", "bot", "ai");

        // ── People & gestures ──
        add("👋", "wave", "hi", "hello", "bye");
        add("🤚", "raised", "hand", "stop");
        add("✋", "raised", "hand", "stop", "five");
        add("🖖", "vulcan", "spock", "live", "long");
        add("👌", "ok", "okay", "perfect");
        add("✌️", "peace", "victory");
        add("🤞", "crossed", "fingers", "luck", "hope");
        add("🤟", "love", "you", "rock");
        add("🤘", "rock", "horns", "metal");
        add("🤙", "call", "me", "hang", "loose");
        add("👈", "left", "point");
        add("👉", "right", "point");
        add("👆", "up", "point");
        add("👇", "down", "point");
        add("☝️", "up", "index", "one");
        add("👍", "thumbs", "up", "yes", "like", "good");
        add("👎", "thumbs", "down", "no", "dislike", "bad");
        add("✊", "fist", "punch");
        add("👊", "fist", "bump", "punch");
        add("🤛", "left", "fist", "bump");
        add("🤜", "right", "fist", "bump");
        add("👏", "clap", "applause");
        add("🙌", "raised", "hands", "praise", "yay");
        add("👐", "open", "hands");
        add("🤲", "palms", "up");
        add("🤝", "handshake", "deal", "agree");
        add("🙏", "pray", "please", "thanks", "namaste");
        add("💪", "muscle", "strong", "flex");
        add("👀", "eyes", "look", "see");
        add("👁️", "eye", "see");
        add("👅", "tongue", "lick");
        add("👄", "mouth", "lips");
        add("💋", "kiss", "lipstick", "lips");
        add("👶", "baby");
        add("🧒", "child", "kid");
        add("👦", "boy");
        add("👧", "girl");
        add("🧑", "person", "adult");
        add("👨", "man");
        add("👩", "woman");
        add("🧔", "beard");
        add("🧓", "older", "person");
        add("👴", "old", "man", "grandpa");
        add("👵", "old", "woman", "grandma");
        add("🙋", "raising", "hand", "question");
        add("🙇", "bow", "sorry", "apologize");
        add("🤦", "facepalm", "frustrated");
        add("🤷", "shrug", "idk");
        add("👮", "cop", "police", "officer");
        add("🕵️", "detective", "spy");
        add("👷", "construction", "worker");
        add("🤴", "prince", "king");
        add("👸", "princess", "queen");
        add("🥷", "ninja");
        add("🎅", "santa", "christmas");
        add("🤶", "mrs", "claus", "christmas");
        add("🦸", "hero", "superhero");
        add("🦹", "villain", "supervillain");
        add("🧙", "mage", "wizard");
        add("🧚", "fairy");
        add("🧛", "vampire");
        add("🧜", "mermaid", "merman");
        add("🧝", "elf");
        add("🧞", "genie");
        add("🧟", "zombie");
        add("🚶", "walk", "walking");
        add("🏃", "run", "running", "jog");
        add("💃", "dance", "dancing");
        add("🕺", "dance", "man", "dancing");
        add("🧘", "meditate", "yoga", "zen");

        // ── Animals & nature ──
        add("🐶", "dog", "puppy", "doggo");
        add("🐱", "cat", "kitten", "kitty", "meow");
        add("🐭", "mouse");
        add("🐹", "hamster");
        add("🐰", "rabbit", "bunny");
        add("🦊", "fox");
        add("🐻", "bear");
        add("🐼", "panda");
        add("🐨", "koala");
        add("🐯", "tiger");
        add("🦁", "lion");
        add("🐮", "cow");
        add("🐷", "pig");
        add("🐸", "frog");
        add("🐵", "monkey");
        add("🙈", "see", "no", "evil", "monkey");
        add("🙉", "hear", "no", "evil", "monkey");
        add("🙊", "speak", "no", "evil", "monkey");
        add("🐒", "monkey");
        add("🐔", "chicken");
        add("🐧", "penguin");
        add("🐦", "bird");
        add("🐤", "chick", "baby", "chicken");
        add("🦆", "duck");
        add("🦅", "eagle");
        add("🦉", "owl");
        add("🦇", "bat");
        add("🐺", "wolf");
        add("🐗", "boar", "pig");
        add("🐴", "horse");
        add("🦄", "unicorn");
        add("🐝", "bee", "honey");
        add("🐛", "bug", "caterpillar");
        add("🦋", "butterfly");
        add("🐌", "snail");
        add("🐞", "ladybug");
        add("🐜", "ant");
        add("🕷️", "spider");
        add("🦂", "scorpion");
        add("🐢", "turtle", "tortoise");
        add("🐍", "snake");
        add("🦎", "lizard");
        add("🦖", "trex", "dinosaur");
        add("🦕", "dinosaur", "sauropod");
        add("🐙", "octopus");
        add("🦑", "squid");
        add("🦐", "shrimp");
        add("🦀", "crab");
        add("🐠", "fish", "tropical");
        add("🐟", "fish");
        add("🐬", "dolphin");
        add("🐳", "whale");
        add("🦈", "shark");
        add("🐊", "crocodile", "alligator");
        add("🦓", "zebra");
        add("🦍", "gorilla");
        add("🐘", "elephant");
        add("🦏", "rhino");
        add("🐪", "camel");
        add("🦒", "giraffe");
        add("🐎", "horse", "racehorse");
        add("🐑", "sheep");
        add("🐐", "goat");
        add("🦌", "deer");
        add("🐕", "dog");
        add("🌵", "cactus");
        add("🎄", "christmas", "tree");
        add("🌲", "tree", "evergreen");
        add("🌳", "tree", "deciduous");
        add("🌴", "palm", "tree");
        add("🌱", "seedling", "sprout", "plant");
        add("🌿", "herb", "leaves");
        add("☘️", "shamrock", "luck");
        add("🍀", "clover", "luck");
        add("🍃", "leaf", "wind");
        add("🍂", "leaves", "fall", "autumn");
        add("🍁", "maple", "leaf", "canada");
        add("🍄", "mushroom");
        add("🌹", "rose", "flower");
        add("🌺", "hibiscus", "flower");
        add("🌸", "cherry", "blossom", "sakura", "flower");
        add("🌼", "flower", "daisy");
        add("🌻", "sunflower", "flower");
        add("🌞", "sun", "happy");
        add("🌙", "moon", "crescent", "night");
        add("⭐", "star");
        add("🌟", "star", "glowing", "sparkle");
        add("✨", "sparkles", "shine");
        add("⚡", "lightning", "bolt", "fast");
        add("🔥", "fire", "lit", "hot", "flame");
        add("🌈", "rainbow", "pride");
        add("☀️", "sun", "sunny");
        add("☁️", "cloud", "cloudy");
        add("🌧️", "rain", "rainy");
        add("⛈️", "storm", "thunder");
        add("❄️", "snowflake", "snow", "cold");
        add("☃️", "snowman");
        add("☔", "umbrella", "rain");
        add("🌊", "wave", "ocean", "water");

        // ── Food & drink ──
        add("🍎", "apple", "red", "fruit");
        add("🍐", "pear", "fruit");
        add("🍊", "orange", "tangerine", "fruit");
        add("🍋", "lemon", "fruit");
        add("🍌", "banana", "fruit");
        add("🍉", "watermelon", "fruit");
        add("🍇", "grapes", "fruit");
        add("🍓", "strawberry", "fruit");
        add("🫐", "blueberry", "fruit");
        add("🍒", "cherries", "fruit");
        add("🍑", "peach", "butt", "fruit");
        add("🥭", "mango", "fruit");
        add("🍍", "pineapple", "fruit");
        add("🥥", "coconut", "fruit");
        add("🥝", "kiwi", "fruit");
        add("🍅", "tomato", "fruit");
        add("🍆", "eggplant", "aubergine", "veggie");
        add("🥑", "avocado");
        add("🥦", "broccoli", "veggie");
        add("🥬", "lettuce", "leafy", "greens");
        add("🥒", "cucumber", "pickle");
        add("🌶️", "pepper", "chili", "hot", "spicy");
        add("🌽", "corn");
        add("🥕", "carrot");
        add("🧄", "garlic");
        add("🧅", "onion");
        add("🥔", "potato");
        add("🍞", "bread", "loaf");
        add("🥐", "croissant");
        add("🥖", "baguette", "bread");
        add("🧀", "cheese");
        add("🥚", "egg");
        add("🍳", "egg", "cooking", "fried");
        add("🥞", "pancakes");
        add("🧇", "waffle");
        add("🥓", "bacon");
        add("🥩", "steak", "meat");
        add("🍗", "drumstick", "chicken", "meat");
        add("🍖", "meat", "bone");
        add("🌭", "hotdog", "hot", "dog");
        add("🍔", "burger", "hamburger");
        add("🍟", "fries", "french");
        add("🍕", "pizza");
        add("🥪", "sandwich");
        add("🌮", "taco");
        add("🌯", "burrito");
        add("🥗", "salad");
        add("🍝", "spaghetti", "pasta", "noodle");
        add("🍜", "ramen", "noodles", "soup");
        add("🍣", "sushi");
        add("🍱", "bento", "lunch", "box");
        add("🥟", "dumpling");
        add("🍤", "shrimp", "tempura", "fried");
        add("🍙", "rice", "ball", "onigiri");
        add("🍚", "rice");
        add("🍦", "ice", "cream", "soft");
        add("🍨", "ice", "cream", "scoop");
        add("🍰", "cake", "shortcake");
        add("🎂", "birthday", "cake");
        add("🍭", "lollipop", "candy");
        add("🍬", "candy", "sweet");
        add("🍫", "chocolate", "bar");
        add("🍿", "popcorn");
        add("🍩", "donut", "doughnut");
        add("🍪", "cookie", "biscuit");
        add("🥛", "milk");
        add("☕", "coffee", "tea", "hot");
        add("🍵", "tea", "matcha");
        add("🥤", "cup", "soda", "drink");
        add("🧋", "boba", "bubble", "tea");
        add("🍺", "beer", "mug");
        add("🍻", "beers", "cheers");
        add("🥂", "cheers", "champagne", "toast");
        add("🍷", "wine");
        add("🍸", "cocktail", "martini");
        add("🍹", "tropical", "drink", "cocktail");
        add("🍾", "champagne", "bottle", "pop");

        // ── Travel & places ──
        add("🚗", "car", "auto");
        add("🚕", "taxi", "cab");
        add("🚙", "suv");
        add("🚌", "bus");
        add("🏎️", "racing", "car", "race");
        add("🚓", "police", "car");
        add("🚑", "ambulance");
        add("🚒", "fire", "truck");
        add("🚜", "tractor");
        add("🛴", "scooter", "kick");
        add("🚲", "bicycle", "bike");
        add("🏍️", "motorcycle", "bike");
        add("✈️", "airplane", "flight", "fly", "travel");
        add("🛫", "takeoff", "plane");
        add("🛬", "landing", "plane");
        add("🚀", "rocket", "launch", "space");
        add("🛸", "ufo", "saucer");
        add("🚁", "helicopter");
        add("⛵", "sailboat");
        add("🚤", "speedboat");
        add("🚢", "ship", "boat");
        add("⚓", "anchor");
        add("🚦", "traffic", "light");
        add("🗽", "liberty", "statue", "nyc");
        add("🗼", "tokyo", "tower");
        add("🏰", "castle");
        add("🎡", "ferris", "wheel");
        add("🎢", "roller", "coaster");
        add("🏖️", "beach");
        add("🏝️", "island");
        add("🌋", "volcano");
        add("⛰️", "mountain");
        add("🏔️", "snow", "mountain");
        add("🏕️", "camping", "tent");
        add("⛺", "tent");
        add("🏠", "house", "home");
        add("🏡", "house", "garden");
        add("🏢", "office", "building");
        add("🏥", "hospital");
        add("🏨", "hotel");
        add("🏪", "store", "convenience");
        add("🏫", "school");
        add("⛪", "church");
        add("🌅", "sunrise");
        add("🌇", "sunset", "city");
        add("🌃", "night", "city", "stars");
        add("🌉", "bridge", "night");

        // ── Activities ──
        add("⚽", "soccer", "football", "ball");
        add("🏀", "basketball");
        add("🏈", "football", "american");
        add("⚾", "baseball");
        add("🎾", "tennis");
        add("🏐", "volleyball");
        add("🏉", "rugby");
        add("🥏", "frisbee", "disc");
        add("🎱", "pool", "billiards", "8ball");
        add("🏓", "ping", "pong", "table", "tennis");
        add("🏸", "badminton");
        add("🏒", "hockey");
        add("⛳", "golf");
        add("🎣", "fishing");
        add("🥊", "boxing", "glove");
        add("🎽", "running", "shirt");
        add("🛹", "skateboard");
        add("⛸️", "skate", "ice");
        add("🎿", "ski");
        add("🏂", "snowboard");
        add("🏋️", "gym", "lift", "weights");
        add("🚴", "cyclist", "bike");
        add("🏆", "trophy", "winner", "first");
        add("🥇", "gold", "medal", "first");
        add("🥈", "silver", "medal", "second");
        add("🥉", "bronze", "medal", "third");
        add("🎖️", "medal", "military");
        add("🎫", "ticket");
        add("🎭", "theatre", "drama", "mask");
        add("🎨", "art", "palette");
        add("🎬", "movie", "clapper", "film");
        add("🎤", "microphone", "mic", "sing");
        add("🎧", "headphones", "music");
        add("🎼", "music", "score");
        add("🎹", "piano", "music");
        add("🥁", "drum");
        add("🎷", "saxophone", "sax");
        add("🎺", "trumpet");
        add("🎸", "guitar");
        add("🎻", "violin");
        add("🎲", "dice", "game");
        add("🎯", "target", "bullseye", "dart");
        add("🎳", "bowling");
        add("🎮", "controller", "gamepad", "game");
        add("🎰", "slot", "machine", "casino");
        add("🧩", "puzzle", "jigsaw");

        // ── Objects ──
        add("⌚", "watch", "time");
        add("📱", "phone", "mobile", "cell");
        add("💻", "laptop", "computer", "mac");
        add("⌨️", "keyboard");
        add("🖥️", "desktop", "monitor", "computer");
        add("🖨️", "printer");
        add("🖱️", "mouse", "computer");
        add("💾", "floppy", "save", "disk");
        add("💿", "cd", "disc");
        add("📷", "camera", "photo");
        add("📹", "video", "camera");
        add("📺", "tv", "television");
        add("📻", "radio");
        add("🎙️", "microphone", "studio");
        add("⏰", "alarm", "clock");
        add("⏳", "hourglass", "wait");
        add("📡", "satellite", "antenna");
        add("🔋", "battery");
        add("🔌", "plug", "electric");
        add("💡", "bulb", "idea", "light");
        add("🔦", "flashlight", "torch");
        add("🕯️", "candle");
        add("💸", "money", "wings", "flying");
        add("💵", "dollar", "money", "cash");
        add("💰", "money", "bag", "rich");
        add("💳", "credit", "card");
        add("💎", "gem", "diamond");
        add("🔧", "wrench", "tool");
        add("🔨", "hammer", "tool");
        add("🛠️", "tools");
        add("⚙️", "gear", "settings", "cog");
        add("🔫", "gun", "water", "pistol");
        add("💣", "bomb");
        add("🧨", "firecracker");
        add("🛡️", "shield", "protect");
        add("🔮", "crystal", "ball", "magic");
        add("🧸", "teddy", "bear", "toy");
        add("🎁", "gift", "present");
        add("🎈", "balloon", "party");
        add("🎀", "ribbon", "bow");
        add("🎉", "party", "popper", "celebrate", "tada");
        add("🎊", "confetti", "party");
        add("✉️", "envelope", "mail");
        add("📧", "email", "mail");
        add("💌", "love", "letter");
        add("📦", "package", "box");
        add("📅", "calendar", "date");
        add("📋", "clipboard");
        add("📌", "pin", "pushpin");
        add("✂️", "scissors", "cut");
        add("📎", "paperclip");
        add("📏", "ruler", "measure");
        add("✏️", "pencil");
        add("✒️", "pen", "nib");
        add("📝", "memo", "note", "write");
        add("📖", "book", "open", "read");
        add("📚", "books", "library");
        add("🔍", "search", "magnifying", "glass", "find");
        add("🔒", "lock", "locked", "secure");
        add("🔓", "unlock", "unlocked");
        add("🔑", "key");

        // ── Symbols ──
        add("❤️", "heart", "love", "red");
        add("🧡", "heart", "orange");
        add("💛", "heart", "yellow");
        add("💚", "heart", "green");
        add("💙", "heart", "blue");
        add("💜", "heart", "purple");
        add("🖤", "heart", "black");
        add("🤍", "heart", "white");
        add("🤎", "heart", "brown");
        add("💔", "broken", "heart", "breakup");
        add("❣️", "heart", "exclamation");
        add("💕", "two", "hearts", "love");
        add("💞", "revolving", "hearts");
        add("💓", "beating", "heart");
        add("💗", "growing", "heart");
        add("💖", "sparkling", "heart");
        add("💘", "heart", "arrow", "cupid");
        add("💝", "heart", "ribbon", "gift");
        add("♥️", "heart", "suit", "card");
        add("✝️", "cross", "christian");
        add("☪️", "star", "crescent", "islam");
        add("✡️", "star", "david", "jewish");
        add("☮️", "peace");
        add("☯️", "yin", "yang");
        add("♈", "aries", "zodiac");
        add("♉", "taurus", "zodiac");
        add("♊", "gemini", "zodiac");
        add("♋", "cancer", "zodiac");
        add("♌", "leo", "zodiac");
        add("♍", "virgo", "zodiac");
        add("♎", "libra", "zodiac");
        add("♏", "scorpio", "zodiac");
        add("♐", "sagittarius", "zodiac");
        add("♑", "capricorn", "zodiac");
        add("♒", "aquarius", "zodiac");
        add("♓", "pisces", "zodiac");
        add("⚛️", "atom", "science");
        add("☢️", "radioactive", "danger");
        add("☣️", "biohazard", "danger");
        add("✴️", "star", "eight");
        add("❌", "cross", "x", "no", "wrong");
        add("⭕", "circle", "o", "correct");
        add("🛑", "stop", "octagon");
        add("⛔", "no", "entry");
        add("🚫", "no", "prohibited", "forbidden");
        add("💯", "hundred", "100", "perfect");
        add("💢", "anger", "mad", "rage");
        add("❗", "exclamation", "bang");
        add("❓", "question", "mark");
        add("⚠️", "warning", "caution");
        add("♻️", "recycle");
        add("✅", "check", "yes", "tick", "correct");
        add("✔️", "check", "tick");
        add("☑️", "check", "box", "tick");
        add("Ⓜ️", "metro", "circle", "m");
        add("0️⃣", "zero", "0");
        add("1️⃣", "one", "1");
        add("2️⃣", "two", "2");
        add("3️⃣", "three", "3");
        add("4️⃣", "four", "4");
        add("5️⃣", "five", "5");
        add("6️⃣", "six", "6");
        add("7️⃣", "seven", "7");
        add("8️⃣", "eight", "8");
        add("9️⃣", "nine", "9");
        add("🔟", "ten", "10");
        add("#️⃣", "hash", "pound");
        add("▶️", "play", "arrow", "right");
        add("⏸️", "pause");
        add("⏹️", "stop", "square");
        add("⏺️", "record");
        add("🔀", "shuffle");
        add("🔁", "repeat", "loop");
        add("🎵", "music", "note");
        add("🎶", "music", "notes");
        add("➕", "plus", "add");
        add("➖", "minus", "subtract");
        add("➗", "divide", "division");
        add("✖️", "multiply", "times", "x");
        add("💲", "dollar", "sign");
        add("🔴", "red", "circle", "dot");
        add("🟠", "orange", "circle");
        add("🟡", "yellow", "circle");
        add("🟢", "green", "circle");
        add("🔵", "blue", "circle");
        add("🟣", "purple", "circle");
        add("⚫", "black", "circle");
        add("⚪", "white", "circle");
        add("🟥", "red", "square");
        add("🟧", "orange", "square");
        add("🟨", "yellow", "square");
        add("🟩", "green", "square");
        add("🟦", "blue", "square");
        add("🟪", "purple", "square");
        add("⬛", "black", "square");
        add("⬜", "white", "square");
        add("🔔", "bell", "notification");
        add("🔕", "no", "bell", "mute");
        add("📣", "megaphone", "loud");
        add("💬", "speech", "bubble", "chat");
        add("💭", "thought", "bubble", "think");

        // ── Flags ──
        add("🏁", "checkered", "flag", "race", "finish");
        add("🚩", "triangular", "flag");
        add("🏳️", "white", "flag", "surrender");
        add("🏴", "black", "flag");
        add("🏳️‍🌈", "rainbow", "pride", "flag", "lgbtq", "gay");
        add("🏳️‍⚧️", "transgender", "flag", "trans", "pride");
        add("🏴‍☠️", "pirate", "flag");
        add("🇺🇸", "usa", "united", "states", "america", "flag");
        add("🇬🇧", "uk", "united", "kingdom", "britain", "flag");
        add("🇨🇦", "canada", "canadian", "flag");
        add("🇫🇷", "france", "french", "flag");
        add("🇩🇪", "germany", "german", "flag");
        add("🇮🇹", "italy", "italian", "flag");
        add("🇪🇸", "spain", "spanish", "flag");
        add("🇯🇵", "japan", "japanese", "flag");
        add("🇨🇳", "china", "chinese", "flag");
        add("🇰🇷", "korea", "korean", "flag");
        add("🇮🇳", "india", "indian", "flag");
        add("🇧🇷", "brazil", "brazilian", "flag");
        add("🇲🇽", "mexico", "mexican", "flag");
        add("🇦🇺", "australia", "aussie", "flag");
        add("🇷🇺", "russia", "russian", "flag");
    }

    private static void add(String emoji, String... keywords) {
        INDEX.put(emoji, keywords);
    }

    private EmojiSearchIndex() { }

    /** Returns emojis matching {@code query}, ranked exact > prefix > substring
     *  on any of the entry's keywords. Returns an empty list for blank queries
     *  so callers can decide what to show in that state. */
    public static List<String> search(String query) {
        if (query == null) return new ArrayList<>();
        String q = query.toLowerCase(Locale.ROOT).trim();
        if (q.isEmpty()) return new ArrayList<>();

        List<String> exact = new ArrayList<>();
        List<String> prefix = new ArrayList<>();
        List<String> contains = new ArrayList<>();
        for (Map.Entry<String, String[]> e : INDEX.entrySet()) {
            int tier = 3; // 0=exact, 1=prefix, 2=contains, 3=miss
            for (String kw : e.getValue()) {
                if (kw.equals(q)) { tier = 0; break; }
                if (tier > 1 && kw.startsWith(q)) { tier = 1; continue; }
                if (tier > 2 && kw.contains(q)) { tier = 2; }
            }
            switch (tier) {
                case 0: exact.add(e.getKey()); break;
                case 1: prefix.add(e.getKey()); break;
                case 2: contains.add(e.getKey()); break;
                default: break;
            }
        }
        List<String> out = new ArrayList<>(exact.size() + prefix.size() + contains.size());
        out.addAll(exact);
        out.addAll(prefix);
        out.addAll(contains);
        return out;
    }
}
