#!/usr/bin/env node
// Single-source design-system generator. Reads tokens.json and emits
// platform-native files committed alongside this script — no build-time
// coupling, each platform consumes its native artifact as-is.

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(__dirname, "..");

const KNOWN_TYPES = new Set(["color", "dimension", "fontFamily", "fontWeight", "duration", "cubicBezier", "shadow", "typography"]);
const HEX = /^#([0-9a-fA-F]{6}|[0-9a-fA-F]{8})$/;
const DIM = /^-?(\d+(?:\.\d+)?)(px|pt|rem|em)?$/;
const HEADER = "// AUTO-GENERATED by design-system/build.mjs. Edit tokens.json, not this file.";
const XML_HEADER = "<!-- AUTO-GENERATED by design-system/build.mjs. Edit tokens.json, not this file. -->";

const tokens = JSON.parse(readFileSync(join(__dirname, "tokens.json"), "utf8"));
const flat = flatten(tokens);
shapeCheck(flat);

const outputs = {
  androidColors: join(repoRoot, "android/app/src/main/res/values/colors_tokens.xml"),
  androidDimens: join(repoRoot, "android/app/src/main/res/values/dimens_tokens.xml"),
  androidStyles: join(repoRoot, "android/app/src/main/res/values/styles_tokens.xml"),
  ios:           join(repoRoot, "ios/TurtleKeyboard/Generated/BrandTokens.swift"),
  css:           join(repoRoot, "lading-app/lib/design-system.css"),
  preview:       join(__dirname, "preview.html"),
};

writeFile(outputs.androidColors, buildAndroidColors(flat));
writeFile(outputs.androidDimens, buildAndroidDimens(flat));
writeFile(outputs.androidStyles, buildAndroidStyles(flat));
writeFile(outputs.ios,           buildIos(flat));
writeFile(outputs.css,           buildCss(flat));
writeFile(outputs.preview,       buildPreview(flat));

const counts = countByType(flat);
console.log(`design-system: ${counts.color} colors, ${counts.dimension} dimensions, ${counts.typography} text styles → android/ios/css/preview`);

// -- helpers -----------------------------------------------------------------

function flatten(obj, prefix = []) {
  const out = {};
  for (const [k, v] of Object.entries(obj)) {
    if (k.startsWith("$")) continue;
    if (v && typeof v === "object" && "$value" in v) {
      out[[...prefix, k].join(".")] = { value: v.$value, type: v.$type };
    } else if (v && typeof v === "object") {
      Object.assign(out, flatten(v, [...prefix, k]));
    }
  }
  return out;
}

function shapeCheck(flat) {
  const errs = [];
  for (const [key, t] of Object.entries(flat)) {
    if (!t.type || !KNOWN_TYPES.has(t.type)) { errs.push(`${key}: unknown $type "${t.type}"`); continue; }
    if (t.value === undefined || t.value === null) { errs.push(`${key}: missing $value`); continue; }

    if (t.type === "color") {
      if (typeof t.value !== "string" || !HEX.test(t.value)) {
        errs.push(`${key}: $value "${t.value}" is not a hex color (#RRGGBB or #RRGGBBAA)`);
      }
    } else if (t.type === "dimension") {
      if (typeof t.value !== "string" && typeof t.value !== "number") {
        errs.push(`${key}: dimension $value must be string or number`);
      } else if (typeof t.value === "string" && !DIM.test(t.value)) {
        errs.push(`${key}: dimension $value "${t.value}" must match <number>(px|pt|rem|em)`);
      }
    } else if (t.type === "typography") {
      if (typeof t.value !== "object" || Array.isArray(t.value)) {
        errs.push(`${key}: typography $value must be an object`);
      } else {
        for (const f of ["fontFamily", "fontWeight", "fontSize", "lineHeight"]) {
          if (!(f in t.value)) errs.push(`${key}: typography $value missing required "${f}"`);
        }
      }
    }
  }
  if (errs.length) {
    console.error("tokens.json shape errors:");
    for (const e of errs) console.error(`  - ${e}`);
    process.exit(1);
  }
}

function countByType(flat) {
  const c = { color: 0, dimension: 0, typography: 0 };
  for (const t of Object.values(flat)) c[t.type] = (c[t.type] || 0) + 1;
  return c;
}

function snake(name) { return name.replace(/[.-]/g, "_"); }
function camel(name) { return name.replace(/[.-]([a-z0-9])/gi, (_, c) => c.toUpperCase()); }
function kebab(name) { return name.replace(/\./g, "-"); }
function pascal(name) { const c = camel(name); return c[0].toUpperCase() + c.slice(1); }

function parseDim(value) {
  if (typeof value === "number") return value;
  const m = DIM.exec(value);
  if (!m) throw new Error(`Bad dimension: ${value}`);
  return parseFloat(m[1]);
}

function hexToRgba(hex) {
  const m = hex.replace("#", "");
  if (m.length === 6) {
    return [parseInt(m.slice(0,2),16), parseInt(m.slice(2,4),16), parseInt(m.slice(4,6),16), 255];
  }
  if (m.length === 8) {
    return [parseInt(m.slice(2,4),16), parseInt(m.slice(4,6),16), parseInt(m.slice(6,8),16), parseInt(m.slice(0,2),16)];
  }
  throw new Error(`Bad hex literal: ${hex}`);
}

// Android maps fontFamily+weight to its bundled sans-serif variants. Keeps the
// generated styles font-file-free; per-brand custom fonts can be added later.
function androidFontFamily(family, weight) {
  if (family !== "system") return family;
  if (weight >= 800) return "sans-serif-black";
  if (weight >= 500) return "sans-serif-medium";
  if (weight >= 400) return "sans-serif";
  if (weight >= 300) return "sans-serif-light";
  return "sans-serif-thin";
}

function androidStyleSuffix(key) {
  const parts = key.split(".");
  if (parts[0] === "text") parts.shift();
  return parts.map(p => p[0].toUpperCase() + p.slice(1)).join(".");
}

function iosFontWeight(weight) {
  if (weight >= 900) return ".black";
  if (weight >= 800) return ".heavy";
  if (weight >= 700) return ".bold";
  if (weight >= 600) return ".semibold";
  if (weight >= 500) return ".medium";
  if (weight >= 400) return ".regular";
  if (weight >= 300) return ".light";
  if (weight >= 200) return ".thin";
  return ".ultraLight";
}

function cssFontFamily(family) {
  if (family !== "system") return family;
  return "system-ui, -apple-system, BlinkMacSystemFont, \"Segoe UI\", sans-serif";
}

function letterSpacingEm(value) {
  if (value === undefined || value === null || value === "" || value === 0) return 0;
  if (typeof value === "number") return value;
  const m = /^(-?\d+(?:\.\d+)?)(em|px)?$/.exec(value);
  if (!m) return 0;
  return parseFloat(m[1]); // for px we'd need font-size context; em is the canonical form
}

// -- Android emitters --------------------------------------------------------

function buildAndroidColors(flat) {
  const lines = [`<?xml version="1.0" encoding="utf-8"?>`, XML_HEADER, `<resources>`];
  for (const [key, t] of Object.entries(flat)) {
    if (t.type !== "color") continue;
    const [r, g, b, a] = hexToRgba(t.value);
    const alpha = a.toString(16).padStart(2, "0").toUpperCase();
    const rgb = [r, g, b].map(c => c.toString(16).padStart(2, "0").toUpperCase()).join("");
    lines.push(`    <color name="${snake(key)}">#${alpha}${rgb}</color>`);
  }
  lines.push(`</resources>`, "");
  return lines.join("\n");
}

function buildAndroidDimens(flat) {
  const lines = [`<?xml version="1.0" encoding="utf-8"?>`, XML_HEADER, `<resources>`];
  for (const [key, t] of Object.entries(flat)) {
    if (t.type !== "dimension") continue;
    const n = parseDim(t.value);
    lines.push(`    <dimen name="${snake(key)}">${n}dp</dimen>`);
  }
  lines.push(`</resources>`, "");
  return lines.join("\n");
}

function buildAndroidStyles(flat) {
  const lines = [`<?xml version="1.0" encoding="utf-8"?>`, XML_HEADER, `<resources>`];
  for (const [key, t] of Object.entries(flat)) {
    if (t.type !== "typography") continue;
    const v = t.value;
    const family = androidFontFamily(v.fontFamily, Number(v.fontWeight) || 400);
    const size = parseDim(v.fontSize);
    const lineHeight = Number(v.lineHeight);
    const letter = letterSpacingEm(v.letterSpacing);
    const styleName = `TextAppearance.Token.${androidStyleSuffix(key)}`;
    lines.push(`    <style name="${styleName}" parent="">`);
    lines.push(`        <item name="android:fontFamily">${family}</item>`);
    lines.push(`        <item name="android:textSize">${size}sp</item>`);
    if (lineHeight) lines.push(`        <item name="android:lineSpacingMultiplier">${lineHeight}</item>`);
    if (letter)     lines.push(`        <item name="android:letterSpacing">${letter}</item>`);
    lines.push(`    </style>`);
  }
  lines.push(`</resources>`, "");
  return lines.join("\n");
}

// -- iOS emitter -------------------------------------------------------------

function buildIos(flat) {
  const colors = [];
  const spaces = [];
  const texts = [];

  for (const [key, t] of Object.entries(flat)) {
    if (t.type === "color") {
      const [r, g, b, a] = hexToRgba(t.value);
      const fmt = n => (n / 255).toFixed(4);
      colors.push(`    static let ${camel(key)} = UIColor(red: ${fmt(r)}, green: ${fmt(g)}, blue: ${fmt(b)}, alpha: ${fmt(a)})`);
    } else if (t.type === "dimension") {
      spaces.push(`    static let ${camel(key)}: CGFloat = ${parseDim(t.value)}`);
    } else if (t.type === "typography") {
      const v = t.value;
      const family = v.fontFamily === "system" ? "System" : v.fontFamily;
      const size = parseDim(v.fontSize);
      const lh   = Number(v.lineHeight);
      const ls   = letterSpacingEm(v.letterSpacing);
      const w    = iosFontWeight(Number(v.fontWeight) || 400);
      texts.push(`    static let ${camel(key)} = BrandTextStyle(fontFamily: "${family}", fontWeight: ${w}, fontSize: ${size}, lineHeight: ${lh}, letterSpacing: ${ls})`);
    }
  }

  return [
    HEADER,
    `import UIKit`,
    ``,
    `struct BrandTextStyle {`,
    `    let fontFamily: String`,
    `    let fontWeight: UIFont.Weight`,
    `    let fontSize: CGFloat`,
    `    let lineHeight: CGFloat`,
    `    let letterSpacing: CGFloat`,
    `}`,
    ``,
    `enum BrandToken {`,
    ...colors,
    ...(spaces.length ? ["", "    // Spacing", ...spaces] : []),
    ...(texts.length  ? ["", "    // Typography", ...texts]  : []),
    `}`,
    ``,
  ].join("\n");
}

// -- CSS emitter -------------------------------------------------------------

function buildCss(flat) {
  const lines = [`/* AUTO-GENERATED by design-system/build.mjs. Edit tokens.json, not this file. */`, `:root {`];
  for (const [key, t] of Object.entries(flat)) {
    if (t.type === "color") {
      lines.push(`  --${kebab(key)}: ${t.value};`);
    } else if (t.type === "dimension") {
      const n = parseDim(t.value);
      lines.push(`  --${kebab(key)}: ${n}px;`);
    } else if (t.type === "typography") {
      const v = t.value;
      const family = cssFontFamily(v.fontFamily);
      const size = parseDim(v.fontSize);
      lines.push(`  --${kebab(key)}-font-family: ${family};`);
      lines.push(`  --${kebab(key)}-font-weight: ${v.fontWeight};`);
      lines.push(`  --${kebab(key)}-font-size: ${size}px;`);
      lines.push(`  --${kebab(key)}-line-height: ${v.lineHeight};`);
      if (v.letterSpacing) lines.push(`  --${kebab(key)}-letter-spacing: ${v.letterSpacing};`);
    }
  }
  lines.push(`}`, ``);
  return lines.join("\n");
}

// -- Preview emitter ---------------------------------------------------------

function buildPreview(flat) {
  const colors = Object.entries(flat).filter(([_, t]) => t.type === "color");
  const dims   = Object.entries(flat).filter(([_, t]) => t.type === "dimension");
  const types  = Object.entries(flat).filter(([_, t]) => t.type === "typography");

  const rootVars = [
    ...colors.map(([k, t]) => `  --${kebab(k)}: ${t.value};`),
    ...dims.map(([k, t]) => `  --${kebab(k)}: ${parseDim(t.value)}px;`),
  ].join("\n");

  const colorCards = colors.map(([key, t]) => `
        <article class="card color-card">
          <div class="swatch" style="background: ${t.value}"></div>
          <div class="meta">
            <code class="name">${key}</code>
            <code class="value">${t.value.toUpperCase()}</code>
          </div>
        </article>`).join("");

  const spaceRows = dims.map(([key, t]) => {
    const px = parseDim(t.value);
    return `
        <div class="space-row">
          <code class="name">${key}</code>
          <div class="space-bar" style="width: ${px}px;"></div>
          <code class="value">${px}dp · ${px}px</code>
        </div>`;
  }).join("");

  const typeSamples = types.map(([key, t]) => {
    const v = t.value;
    const family = cssFontFamily(v.fontFamily);
    const size = parseDim(v.fontSize);
    const meta = `${v.fontWeight} · ${size}px · ${v.lineHeight} lh${v.letterSpacing && v.letterSpacing !== "0" ? ` · ${v.letterSpacing} tracking` : ""}`;
    return `
        <article class="card type-card">
          <div class="type-sample" style="font-family: ${family}; font-weight: ${v.fontWeight}; font-size: ${size}px; line-height: ${v.lineHeight}; letter-spacing: ${v.letterSpacing || 0};">
            The quick brown fox jumps over the lazy dog
          </div>
          <div class="meta">
            <code class="name">${key}</code>
            <code class="value">${meta}</code>
          </div>
        </article>`;
  }).join("");

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Turtle Keyboard · Design Tokens</title>
<style>
  /* AUTO-GENERATED — page chrome dogfoods the tokens it documents */
  :root {
${rootVars}
    --bg: #0c0c0c;
    --bg-card: #161616;
    --bg-card-hover: #1c1c1c;
    --border: #262626;
    --text: #f5f5f5;
    --text-muted: #9a9a9a;
    --mono: ui-monospace, "SF Mono", "JetBrains Mono", Menlo, Consolas, monospace;
    --sans: system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
  }
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { background: var(--bg); color: var(--text); font-family: var(--sans); padding: var(--space-3xl) var(--space-2xl); line-height: 1.5; }
  main { max-width: 1120px; margin: 0 auto; }

  header { margin-bottom: var(--space-4xl); padding-bottom: var(--space-2xl); border-bottom: 1px solid var(--border); }
  header h1 { font-size: 32px; font-weight: 900; letter-spacing: -0.02em; }
  header h1 .brand { color: var(--brand-green); }
  header p { color: var(--text-muted); margin-top: var(--space-sm); font-family: var(--mono); font-size: 13px; }

  section { margin-bottom: var(--space-4xl); }
  section > h2 { font-size: 13px; font-weight: 600; letter-spacing: 0.16em; text-transform: uppercase; color: var(--text-muted); margin-bottom: var(--space-lg); }

  /* Color grid */
  .grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(220px, 1fr)); gap: var(--space-md); }
  .card { background: var(--bg-card); border: 1px solid var(--border); border-radius: 12px; overflow: hidden; transition: background 120ms ease, transform 120ms ease; }
  .card:hover { background: var(--bg-card-hover); transform: translateY(-1px); }
  .color-card .swatch { aspect-ratio: 16 / 9; }
  .meta { padding: var(--space-md) var(--space-lg); display: flex; align-items: center; justify-content: space-between; gap: var(--space-sm); font-family: var(--mono); font-size: 12px; }
  .meta .name { color: var(--text); }
  .meta .value { color: var(--text-muted); }

  /* Spacing list */
  .space-list { display: flex; flex-direction: column; gap: var(--space-sm); }
  .space-row { display: grid; grid-template-columns: 100px 1fr 160px; align-items: center; gap: var(--space-lg); padding: var(--space-md) var(--space-lg); background: var(--bg-card); border: 1px solid var(--border); border-radius: 12px; }
  .space-row .name { font-family: var(--mono); font-size: 12px; }
  .space-bar { height: 12px; background: var(--brand-green); border-radius: 999px; max-width: 100%; }
  .space-row .value { font-family: var(--mono); font-size: 12px; color: var(--text-muted); text-align: right; }

  /* Typography list */
  .type-list { display: flex; flex-direction: column; gap: var(--space-md); }
  .type-card { padding: var(--space-2xl); }
  .type-sample { color: var(--text); margin-bottom: var(--space-lg); }
  .type-card .meta { padding: 0; border-top: 1px dashed var(--border); padding-top: var(--space-md); }

  footer { color: var(--text-muted); font-family: var(--mono); font-size: 11px; padding-top: var(--space-xl); border-top: 1px solid var(--border); }
</style>
</head>
<body>
<main>
  <header>
    <h1>Turtle Keyboard <span class="brand">/</span> Design Tokens</h1>
    <p>${colors.length} colors · ${dims.length} dimensions · ${types.length} text styles · generated from <code>design-system/tokens.json</code></p>
  </header>

  <section>
    <h2>Color</h2>
    <div class="grid">${colorCards}
    </div>
  </section>

  <section>
    <h2>Spacing</h2>
    <div class="space-list">${spaceRows}
    </div>
  </section>

  <section>
    <h2>Typography</h2>
    <div class="type-list">${typeSamples}
    </div>
  </section>

  <footer>AUTO-GENERATED by design-system/build.mjs — edit tokens.json, regenerate, commit.</footer>
</main>
</body>
</html>
`;
}

// -- I/O ---------------------------------------------------------------------

function writeFile(path, contents) {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, contents);
}
