#!/usr/bin/env node
// Single-source design-system generator. Reads token.json (regenerated from
// the Value.tokens*.json Figma exports via merge-figma.mjs) and emits
// platform-native files committed alongside this script — no build-time
// coupling, each platform consumes its native artifact as-is.

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(__dirname, "..");

const KNOWN_TYPES = new Set(["color", "dimension", "fontFamily", "fontWeight", "duration", "cubicBezier", "shadow", "typography", "string", "number"]);
const HEX = /^#([0-9a-fA-F]{6}|[0-9a-fA-F]{8})$/;
const DIM = /^-?(\d+(?:\.\d+)?)(px|pt|rem|em)?$/;
const HEADER = "// AUTO-GENERATED by design-system/build.mjs. Edit token.json, not this file.";
const XML_HEADER = "<!-- AUTO-GENERATED by design-system/build.mjs. Edit token.json, not this file. -->";

const tokens = JSON.parse(readFileSync(join(__dirname, "token.json"), "utf8"));
const flat = flatten(tokens);
shapeCheck(flat);

const outputs = {
  androidColors: join(repoRoot, "android/app/src/main/res/values/colors_tokens.xml"),
  androidDimens: join(repoRoot, "android/app/src/main/res/values/dimens_tokens.xml"),
  androidStyles: join(repoRoot, "android/app/src/main/res/values/styles_tokens.xml"),
  ios:           join(repoRoot, "ios/TurtleKeyboard/Generated/BrandTokens.swift"),
  css:           join(repoRoot, "lading-app/lib/design-system.css"),
  preview:       join(__dirname, "preview.html"),
};

writeFile(outputs.androidColors, buildAndroidColors(flat));
writeFile(outputs.androidDimens, buildAndroidDimens(flat));
writeFile(outputs.androidStyles, buildAndroidStyles(flat));
writeFile(outputs.ios,           buildIos(flat));
writeFile(outputs.css,           buildCss(flat));
writeFile(outputs.preview,       buildPreview(tokens));

const counts = countByType(flat);
const parts = [
  counts.color       ? `${counts.color} colors`               : null,
  counts.dimension   ? `${counts.dimension} dimensions`        : null,
  counts.typography  ? `${counts.typography} text styles`      : null,
  counts.string      ? `${counts.string} strings`              : null,
  counts.number      ? `${counts.number} numbers`              : null,
].filter(Boolean);
console.log(`design-system: ${parts.join(", ") || "0 tokens"} → android/ios/css/preview`);

// -- helpers -----------------------------------------------------------------

function flatten(obj, prefix = []) {
  const out = {};
  for (const [k, v] of Object.entries(obj)) {
    if (k.startsWith("$")) continue;
    if (!v || typeof v !== "object") continue;
    const slug = slugify(k);
    if (!slug) continue;
    if ("$value" in v && "$type" in v) {
      out[[...prefix, slug].join(".")] = { value: extractValue(v), type: v.$type };
    } else {
      Object.assign(out, flatten(v, [...prefix, slug]));
    }
  }
  return out;
}

// Figma exports color $values as { hex, colorSpace, components, alpha };
// other types may follow if Figma starts exporting dimensions/typography.
// Hand-authored hex strings or numbers pass through unchanged.
function extractValue(node) {
  const v = node.$value;
  if (node.$type === "color" && v && typeof v === "object" && "hex" in v) {
    return String(v.hex).toUpperCase();
  }
  return v;
}

// "Primary Colors" → "primary-colors", "Brown 500" → "brown-500", etc.
// Pass-through for keys already in kebab-case.
function slugify(name) {
  return String(name)
    .toLowerCase()
    .replace(/\s+/g, "-")
    .replace(/[^a-z0-9-]/g, "")
    .replace(/-+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function shapeCheck(flat) {
  const errs = [];
  for (const [key, t] of Object.entries(flat)) {
    if (!t.type || !KNOWN_TYPES.has(t.type)) { errs.push(`${key}: unknown $type "${t.type}"`); continue; }
    if (t.value === undefined || t.value === null) { errs.push(`${key}: missing $value`); continue; }

    if (t.type === "color") {
      if (typeof t.value !== "string" || !HEX.test(t.value)) {
        errs.push(`${key}: $value "${t.value}" is not a hex color (#RRGGBB or #RRGGBBAA)`);
      }
    } else if (t.type === "dimension") {
      if (typeof t.value !== "string" && typeof t.value !== "number") {
        errs.push(`${key}: dimension $value must be string or number`);
      } else if (typeof t.value === "string" && !DIM.test(t.value)) {
        errs.push(`${key}: dimension $value "${t.value}" must match <number>(px|pt|rem|em)`);
      }
    } else if (t.type === "typography") {
      if (typeof t.value !== "object" || Array.isArray(t.value)) {
        errs.push(`${key}: typography $value must be an object`);
      } else {
        for (const f of ["fontFamily", "fontWeight", "fontSize", "lineHeight"]) {
          if (!(f in t.value)) errs.push(`${key}: typography $value missing required "${f}"`);
        }
      }
    } else if (t.type === "string") {
      if (typeof t.value !== "string") {
        errs.push(`${key}: string $value must be a string`);
      }
    } else if (t.type === "number") {
      if (typeof t.value !== "number" || !Number.isFinite(t.value)) {
        errs.push(`${key}: number $value must be a finite number`);
      }
    }
  }
  if (errs.length) {
    console.error("token.json shape errors:");
    for (const e of errs) console.error(`  - ${e}`);
    process.exit(1);
  }
}

function countByType(flat) {
  const c = { color: 0, dimension: 0, typography: 0 };
  for (const t of Object.values(flat)) c[t.type] = (c[t.type] || 0) + 1;
  return c;
}

function snake(name) { return name.replace(/[.-]/g, "_"); }
function camel(name) { return name.replace(/[.-]([a-z0-9])/gi, (_, c) => c.toUpperCase()); }
function kebab(name) { return name.replace(/\./g, "-"); }
function pascal(name) { const c = camel(name); return c[0].toUpperCase() + c.slice(1); }

function parseDim(value) {
  if (typeof value === "number") return value;
  const m = DIM.exec(value);
  if (!m) throw new Error(`Bad dimension: ${value}`);
  return parseFloat(m[1]);
}

function hexToRgba(hex) {
  const m = hex.replace("#", "");
  if (m.length === 6) {
    return [parseInt(m.slice(0,2),16), parseInt(m.slice(2,4),16), parseInt(m.slice(4,6),16), 255];
  }
  if (m.length === 8) {
    return [parseInt(m.slice(2,4),16), parseInt(m.slice(4,6),16), parseInt(m.slice(6,8),16), parseInt(m.slice(0,2),16)];
  }
  throw new Error(`Bad hex literal: ${hex}`);
}

// Android maps fontFamily+weight to its bundled sans-serif variants. Keeps the
// generated styles font-file-free; per-brand custom fonts can be added later.
function androidFontFamily(family, weight) {
  if (family !== "system") return family;
  if (weight >= 800) return "sans-serif-black";
  if (weight >= 500) return "sans-serif-medium";
  if (weight >= 400) return "sans-serif";
  if (weight >= 300) return "sans-serif-light";
  return "sans-serif-thin";
}

function androidStyleSuffix(key) {
  const parts = key.split(".");
  if (parts[0] === "text") parts.shift();
  return parts.map(p => p[0].toUpperCase() + p.slice(1)).join(".");
}

function iosFontWeight(weight) {
  if (weight >= 900) return ".black";
  if (weight >= 800) return ".heavy";
  if (weight >= 700) return ".bold";
  if (weight >= 600) return ".semibold";
  if (weight >= 500) return ".medium";
  if (weight >= 400) return ".regular";
  if (weight >= 300) return ".light";
  if (weight >= 200) return ".thin";
  return ".ultraLight";
}

function cssFontFamily(family) {
  if (family !== "system") return family;
  return "system-ui, -apple-system, BlinkMacSystemFont, \"Segoe UI\", sans-serif";
}

function letterSpacingEm(value) {
  if (value === undefined || value === null || value === "" || value === 0) return 0;
  if (typeof value === "number") return value;
  const m = /^(-?\d+(?:\.\d+)?)(em|px)?$/.exec(value);
  if (!m) return 0;
  return parseFloat(m[1]); // for px we'd need font-size context; em is the canonical form
}

// -- Android emitters --------------------------------------------------------

function buildAndroidColors(flat) {
  const lines = [`<?xml version="1.0" encoding="utf-8"?>`, XML_HEADER, `<resources>`];
  for (const [key, t] of Object.entries(flat)) {
    if (t.type !== "color") continue;
    const [r, g, b, a] = hexToRgba(t.value);
    const alpha = a.toString(16).padStart(2, "0").toUpperCase();
    const rgb = [r, g, b].map(c => c.toString(16).padStart(2, "0").toUpperCase()).join("");
    lines.push(`    <color name="${snake(key)}">#${alpha}${rgb}</color>`);
  }
  lines.push(`</resources>`, "");
  return lines.join("\n");
}

function buildAndroidDimens(flat) {
  const lines = [`<?xml version="1.0" encoding="utf-8"?>`, XML_HEADER, `<resources>`];
  for (const [key, t] of Object.entries(flat)) {
    if (t.type !== "dimension" && t.type !== "number") continue;
    const n = parseDim(t.value);
    lines.push(`    <dimen name="${snake(key)}">${n}dp</dimen>`);
  }
  lines.push(`</resources>`, "");
  return lines.join("\n");
}

function buildAndroidStyles(flat) {
  const lines = [`<?xml version="1.0" encoding="utf-8"?>`, XML_HEADER, `<resources>`];
  for (const [key, t] of Object.entries(flat)) {
    if (t.type !== "typography") continue;
    const v = t.value;
    const family = androidFontFamily(v.fontFamily, Number(v.fontWeight) || 400);
    const size = parseDim(v.fontSize);
    const lineHeight = Number(v.lineHeight);
    const letter = letterSpacingEm(v.letterSpacing);
    const styleName = `TextAppearance.Token.${androidStyleSuffix(key)}`;
    lines.push(`    <style name="${styleName}" parent="">`);
    lines.push(`        <item name="android:fontFamily">${family}</item>`);
    lines.push(`        <item name="android:textSize">${size}sp</item>`);
    if (lineHeight) lines.push(`        <item name="android:lineSpacingMultiplier">${lineHeight}</item>`);
    if (letter)     lines.push(`        <item name="android:letterSpacing">${letter}</item>`);
    lines.push(`    </style>`);
  }
  lines.push(`</resources>`, "");
  return lines.join("\n");
}

// -- iOS emitter -------------------------------------------------------------

function buildIos(flat) {
  const colors = [];
  const spaces = [];
  const texts = [];

  for (const [key, t] of Object.entries(flat)) {
    if (t.type === "color") {
      const [r, g, b, a] = hexToRgba(t.value);
      const fmt = n => (n / 255).toFixed(4);
      colors.push(`    static let ${camel(key)} = UIColor(red: ${fmt(r)}, green: ${fmt(g)}, blue: ${fmt(b)}, alpha: ${fmt(a)})`);
    } else if (t.type === "dimension" || t.type === "number") {
      spaces.push(`    static let ${camel(key)}: CGFloat = ${parseDim(t.value)}`);
    } else if (t.type === "typography") {
      const v = t.value;
      const family = v.fontFamily === "system" ? "System" : v.fontFamily;
      const size = parseDim(v.fontSize);
      const lh   = Number(v.lineHeight);
      const ls   = letterSpacingEm(v.letterSpacing);
      const w    = iosFontWeight(Number(v.fontWeight) || 400);
      texts.push(`    static let ${camel(key)} = BrandTextStyle(fontFamily: "${family}", fontWeight: ${w}, fontSize: ${size}, lineHeight: ${lh}, letterSpacing: ${ls})`);
    }
  }

  return [
    HEADER,
    `import UIKit`,
    ``,
    `struct BrandTextStyle {`,
    `    let fontFamily: String`,
    `    let fontWeight: UIFont.Weight`,
    `    let fontSize: CGFloat`,
    `    let lineHeight: CGFloat`,
    `    let letterSpacing: CGFloat`,
    `}`,
    ``,
    `enum BrandToken {`,
    ...colors,
    ...(spaces.length ? ["", "    // Spacing", ...spaces] : []),
    ...(texts.length  ? ["", "    // Typography", ...texts]  : []),
    `}`,
    ``,
  ].join("\n");
}

// -- CSS emitter -------------------------------------------------------------

function buildCss(flat) {
  const lines = [`/* AUTO-GENERATED by design-system/build.mjs. Edit token.json, not this file. */`, `:root {`];
  for (const [key, t] of Object.entries(flat)) {
    if (t.type === "color") {
      lines.push(`  --${kebab(key)}: ${t.value};`);
    } else if (t.type === "dimension") {
      const n = parseDim(t.value);
      lines.push(`  --${kebab(key)}: ${n}px;`);
    } else if (t.type === "string") {
      lines.push(`  --${kebab(key)}: ${JSON.stringify(t.value)};`);
    } else if (t.type === "number") {
      lines.push(`  --${kebab(key)}: ${t.value}px;`);
    } else if (t.type === "typography") {
      const v = t.value;
      const family = cssFontFamily(v.fontFamily);
      const size = parseDim(v.fontSize);
      lines.push(`  --${kebab(key)}-font-family: ${family};`);
      lines.push(`  --${kebab(key)}-font-weight: ${v.fontWeight};`);
      lines.push(`  --${kebab(key)}-font-size: ${size}px;`);
      lines.push(`  --${kebab(key)}-line-height: ${v.lineHeight};`);
      if (v.letterSpacing) lines.push(`  --${kebab(key)}-letter-spacing: ${v.letterSpacing};`);
    }
  }
  lines.push(`}`, ``);
  return lines.join("\n");
}

// -- Preview emitter ---------------------------------------------------------
//
// Walks the raw tokens tree (not the flattened map) so per-group structure and
// Figma round-trip metadata ($extensions.com.figma.variableId, .scopes) survive
// into the rendered page. Numeric-keyed groups (Brown 50–1000) render as a
// continuous scale strip + attribution table; everything else renders as cards.
// Page chrome is palette-led — the preview is an artifact of the palette, not
// a generic dev tool.

function buildPreview(rawTokens) {
  const sections = collectSections(rawTokens);
  const totalColors = sections
    .filter(s => s.kind === "color")
    .reduce((n, s) => n + s.leaves.length, 0);
  const totalType = sections
    .filter(s => s.kind === "typography")
    .reduce((n, s) => n + s.leaves.length, 0);

  // Each leaf gets its emitted-by-platform names attached so the preview can
  // show the Figma→code bridge inline (the point of having a design system).
  for (const section of sections) {
    for (const leaf of section.leaves) {
      leaf.platforms = platformNames(leaf.slug);
    }
  }

  const sectionsHtml = sections.map(s => {
    if (s.kind === "typography")  return renderTypographySection(s);
    if (s.kind === "text-style")  return renderTextStyleSection(s);
    if (s.kind === "number")      return renderNumberSection(s);
    if (s.kind === "string-list") return renderStringListSection(s);
    if (s.isScale)                return renderScaleSection(s);
    return renderNamedSection(s);
  }).join("\n");

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Turtle Keyboard · Design Tokens</title>
<style>
  /* AUTO-GENERATED — chrome uses tokens from this very set:
     section-fg = Main Brand, rules = Grey 07, muted = Grey 01, etc. */
  :root {
    --page-bg:      #F7FFF1;   /* Low green / 02 */
    --page-fg:      #222222;   /* Black / 02 */
    --page-muted:   #979C9E;   /* Grey / 01 */
    --page-rule:    #DCDFDD;   /* Grey / 07 */
    --section-fg:   #009F69;   /* Main Brand */
    --card-bg:      #FFFFFF;
    --card-shadow:  0 1px 2px rgba(0, 0, 0, 0.04), 0 2px 8px rgba(0, 159, 105, 0.06);
    --mono: ui-monospace, "SF Mono", "JetBrains Mono", Menlo, Consolas, monospace;
    --sans: system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Inter, sans-serif;
  }
  /* Skip painting/layout for off-screen sections — biggest win at ~1500 nodes. */
  section { content-visibility: auto; contain-intrinsic-size: 0 600px; }
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body {
    background: var(--page-bg); color: var(--page-fg);
    font-family: var(--sans); line-height: 1.5;
    padding: 56px 32px 96px;
  }
  main { max-width: 1280px; margin: 0 auto; }

  header {
    display: flex; align-items: flex-end; justify-content: space-between; gap: 32px;
    padding-bottom: 28px; margin-bottom: 32px;
    border-bottom: 1px solid var(--page-rule);
  }
  header h1 { font-size: 44px; font-weight: 900; letter-spacing: -0.025em; color: var(--section-fg); }
  header h1 .slash { color: var(--page-fg); opacity: 0.35; margin: 0 4px; font-weight: 500; }
  header .stats {
    font-family: var(--mono); font-size: 12px; color: var(--page-muted);
    text-align: right; line-height: 1.7;
  }
  header .stats strong { color: var(--section-fg); font-weight: 700; }

  /* Anatomy — show the system, not just the swatches */
  .anatomy {
    background: var(--card-bg); border-radius: 14px;
    padding: 24px 28px; margin-bottom: 56px;
    box-shadow: var(--card-shadow);
    display: grid; grid-template-columns: minmax(0, 1fr) auto; gap: 32px;
    align-items: center;
  }
  .anatomy h2 {
    font-size: 11px; font-weight: 800; text-transform: uppercase;
    letter-spacing: 0.18em; color: var(--page-muted); margin-bottom: 8px;
  }
  .anatomy p {
    font-size: 14px; line-height: 1.55; color: var(--page-fg);
    max-width: 56ch;
  }
  .anatomy p code {
    font-family: var(--mono); font-size: 12px;
    background: var(--page-bg); padding: 1px 5px; border-radius: 3px;
    color: var(--section-fg);
  }
  .anatomy-flow {
    font-family: var(--mono); font-size: 11px; line-height: 1.85;
    color: var(--page-fg); white-space: pre;
  }
  .anatomy-flow .arrow { color: var(--page-muted); }
  .anatomy-flow .lane { color: var(--section-fg); font-weight: 700; }

  section { margin-bottom: 56px; }
  .section-head {
    display: flex; align-items: baseline; justify-content: space-between;
    margin-bottom: 18px;
  }
  .section-head h2 {
    font-size: 13px; font-weight: 800; text-transform: uppercase;
    letter-spacing: 0.16em; color: var(--page-muted);
    display: flex; align-items: center; gap: 10px;
  }
  .section-head h2 .tier {
    font-family: var(--mono); font-size: 9px; font-weight: 600;
    text-transform: uppercase; letter-spacing: 0.12em;
    color: var(--section-fg); background: var(--page-bg);
    border: 1px solid var(--page-rule);
    padding: 2px 6px; border-radius: 4px;
  }
  .section-head .badge {
    font-family: var(--mono); font-size: 10px; font-weight: 600;
    text-transform: uppercase; letter-spacing: 0.1em;
    color: var(--page-muted);
    padding: 4px 8px; border: 1px solid var(--page-rule); border-radius: 999px;
    background: var(--card-bg);
  }

  /* Named cards (Primary Colors, Secondary Colors) */
  .card-grid {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(260px, 1fr));
    gap: 16px;
  }
  .card {
    background: var(--card-bg);
    border-radius: 14px; overflow: hidden;
    box-shadow: var(--card-shadow);
    display: flex; flex-direction: column;
  }
  .swatch {
    aspect-ratio: 5 / 3;
    display: flex; align-items: flex-end;
    padding: 14px 16px;
    font-family: var(--mono); font-size: 13px; font-weight: 600;
    letter-spacing: 0.04em;
  }
  .card .meta { padding: 16px 18px 18px; }
  .card .name {
    font-size: 17px; font-weight: 700;
    color: var(--page-fg); margin-bottom: 2px;
  }
  .card .slug {
    font-family: var(--mono); font-size: 12px; color: var(--page-muted);
    display: block; margin-bottom: 14px;
  }
  .card dl {
    display: grid; grid-template-columns: 70px 1fr; gap: 4px 12px;
    font-size: 11px;
    padding-top: 12px; border-top: 1px solid var(--page-rule);
  }
  .card dt {
    font-family: var(--mono); color: var(--page-muted);
    text-transform: uppercase; letter-spacing: 0.08em; font-size: 10px;
    align-self: center;
  }
  .card dd {
    font-family: var(--mono); color: var(--page-fg);
    word-break: break-all;
  }
  .card .platforms {
    margin-top: 12px; padding-top: 12px;
    border-top: 1px solid var(--page-rule);
    display: grid; gap: 4px;
    font-family: var(--mono); font-size: 11px;
  }
  .card .platforms .row {
    display: grid; grid-template-columns: 56px 1fr; gap: 10px; align-items: baseline;
  }
  .card .platforms .lane {
    text-transform: uppercase; letter-spacing: 0.08em; font-size: 9px; font-weight: 700;
    color: var(--page-muted);
  }
  .card .platforms .ref { color: var(--page-fg); word-break: break-all; }

  /* Scale strip (Brown 50–1000, Blue 50–1000) */
  .scale {
    display: flex;
    border-radius: 14px; overflow: hidden;
    box-shadow: var(--card-shadow);
    margin-bottom: 14px;
  }
  .scale-cell {
    flex: 1; aspect-ratio: 1 / 1.7;
    display: flex; flex-direction: column;
    align-items: flex-start; justify-content: space-between;
    padding: 14px 10px;
    font-family: var(--mono);
  }
  .scale-cell .step { font-size: 14px; font-weight: 800; letter-spacing: 0.03em; }
  .scale-cell .hex {
    font-size: 10px; opacity: 0.72;
    letter-spacing: 0.06em; text-transform: uppercase;
  }
  .scale-table {
    width: 100%; border-collapse: collapse;
    font-family: var(--mono); font-size: 12px;
    background: var(--card-bg); border-radius: 12px; overflow: hidden;
    box-shadow: var(--card-shadow);
  }
  .scale-table thead th {
    text-align: left; padding: 10px 14px;
    font-size: 10px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.1em;
    color: var(--page-muted);
    border-bottom: 1px solid var(--page-rule);
    background: var(--page-bg);
  }
  .scale-table tbody td { padding: 10px 14px; color: var(--page-fg); }
  .scale-table tbody tr { border-bottom: 1px solid var(--page-rule); }
  .scale-table tbody tr:last-child { border-bottom: none; }
  .scale-table .swatch-dot {
    display: inline-block; width: 12px; height: 12px;
    border-radius: 999px; margin-right: 10px; vertical-align: -2px;
    border: 1px solid rgba(0, 0, 0, 0.08);
  }
  .scale-table .muted { color: var(--page-muted); }

  /* Typography blocks */
  .type-grid { display: grid; gap: 24px; }
  .type-block {
    background: var(--card-bg); border-radius: 14px; overflow: hidden;
    box-shadow: var(--card-shadow); padding: 28px 28px 0;
  }
  .type-sample {
    font-size: 38px; line-height: 1.15; font-weight: 500;
    color: var(--section-fg); letter-spacing: -0.015em;
    margin-bottom: 16px;
  }
  .type-meta {
    display: flex; align-items: baseline; justify-content: space-between;
    padding-bottom: 16px; border-bottom: 1px solid var(--page-rule);
    margin-bottom: 0;
  }
  .type-meta .family {
    font-family: var(--mono); font-size: 13px; font-weight: 700;
    color: var(--page-fg);
  }
  .type-meta .count {
    font-family: var(--mono); font-size: 10px; text-transform: uppercase;
    letter-spacing: 0.1em; color: var(--page-muted);
  }
  .type-block .scale-table {
    margin: 0 -28px; width: calc(100% + 56px);
    border-radius: 0; box-shadow: none;
  }

  /* Number tiles (radius / spacing visualisation) */
  .num-grid {
    display: flex; flex-wrap: wrap; gap: 16px;
    background: var(--card-bg); border-radius: 14px; padding: 24px;
    box-shadow: var(--card-shadow); margin-bottom: 16px;
    align-items: flex-end;
  }
  .num-tile {
    display: flex; flex-direction: column; align-items: center;
    gap: 8px; min-width: 64px;
  }
  .num-swatch {
    width: 64px; height: 64px;
    background: var(--section-fg);
  }
  .num-step {
    font-family: var(--mono); font-size: 11px; font-weight: 700;
    color: var(--page-fg); letter-spacing: 0.04em;
  }
  .num-value {
    font-family: var(--mono); font-size: 10px;
    color: var(--page-muted); letter-spacing: 0.06em;
  }

  /* Text-style cards (composed typography specs) */
  .ts-grid { display: grid; gap: 16px; }
  .ts-card {
    background: var(--card-bg); border-radius: 14px;
    box-shadow: var(--card-shadow);
    display: grid; grid-template-columns: minmax(0, 1fr) 320px; gap: 0;
    align-items: stretch;
  }
  .ts-sample {
    padding: 32px 32px; color: var(--page-fg);
    border-right: 1px solid var(--page-rule);
    display: flex; align-items: center; min-height: 120px;
  }
  .ts-meta { padding: 20px 24px; font-family: var(--mono); font-size: 11px; }
  .ts-meta .slug {
    display: block; font-weight: 700; color: var(--section-fg);
    font-size: 12px; margin-bottom: 14px;
    word-break: break-all;
  }
  .ts-spec, .ts-extra {
    display: grid; grid-template-columns: 110px 1fr; gap: 4px 12px;
  }
  .ts-spec { padding-bottom: 12px; margin-bottom: 12px; border-bottom: 1px solid var(--page-rule); }
  .ts-spec dt, .ts-extra dt {
    text-transform: uppercase; letter-spacing: 0.08em; font-size: 10px;
    color: var(--page-muted); align-self: center;
  }
  .ts-spec dd, .ts-extra dd { color: var(--page-fg); word-break: break-all; }
  @media (max-width: 720px) {
    .ts-card { grid-template-columns: 1fr; }
    .ts-sample { border-right: 0; border-bottom: 1px solid var(--page-rule); }
  }

  footer {
    font-family: var(--mono); font-size: 11px;
    color: var(--page-muted);
    margin-top: 80px; padding-top: 24px;
    border-top: 1px solid var(--page-rule);
  }
  footer code { color: var(--section-fg); }
</style>
</head>
<body>
<main>
  <header>
    <h1>Turtle Keyboard<span class="slash">/</span>Design Tokens</h1>
    <div class="stats">
      <strong>${totalColors}</strong> colors${totalType ? ` · <strong>${totalType}</strong> typography tokens` : ""} across <strong>${sections.length}</strong> collections<br>
      synced from <code>design-system/token.json</code>
    </div>
  </header>

  <div class="anatomy">
    <div>
      <h2>Anatomy</h2>
      <p>
        Figma Variables are exported per collection as <code>Value.tokens*.json</code>,
        merged into a single <code>token.json</code> by <code>merge-figma.mjs</code>,
        and emitted to four platform targets by <code>build.mjs</code>. Each token
        below shows its generated reference on every target — the bridge from
        design to code is the whole point.
      </p>
    </div>
<div class="anatomy-flow">Figma Variables
  <span class="arrow">↓ export per collection</span>
Value.tokens*.json
  <span class="arrow">↓ merge-figma.mjs</span>
token.json  <span class="arrow">(W3C DTCG)</span>
  <span class="arrow">↓ build.mjs</span>
  <span class="lane">├── Android</span>  <span class="arrow">R.color.<em>{slug}</em></span>
  <span class="lane">├── iOS    </span>  <span class="arrow">BrandToken.<em>{slug}</em></span>
  <span class="lane">├── Landing</span>  <span class="arrow">var(--<em>{slug}</em>)</span>
  <span class="lane">└── Preview</span>  <span class="arrow">you are here</span></div>
  </div>

${sectionsHtml}

  <footer>AUTO-GENERATED by <code>design-system/build.mjs</code> — every Figma re-export rewrites this page.</footer>
</main>
</body>
</html>
`;
}

function collectSections(rawTokens) {
  const sections = [];
  const rootStrings = [];

  for (const [groupName, groupValue] of Object.entries(rawTokens)) {
    if (groupName.startsWith("$")) continue;
    if (!groupValue || typeof groupValue !== "object") continue;

    // Root-level string leaf (legacy flat-fonts export) — collect into a
    // synthetic Typography section at the end.
    if ("$value" in groupValue && groupValue.$type === "string") {
      const ext = groupValue.$extensions || {};
      rootStrings.push({
        name: groupName,
        slug: slugify(groupName),
        value: groupValue.$value,
        figmaId: ext["com.figma.variableId"] || null,
        scopes: ext["com.figma.scopes"] || null,
      });
      continue;
    }
    if ("$value" in groupValue) continue;

    const buckets = { colors: [], numbers: [], strings: [], textStyles: [] };
    walkGroup(groupValue, [groupName], buckets);

    // Order: text-styles first (richest), then colors, then numbers, then
    // any leftover plain strings. Each top-level group can fan out into
    // multiple kinds if it mixes content.
    if (buckets.textStyles.length > 0) {
      sections.push({ name: groupName, leaves: buckets.textStyles, kind: "text-style" });
    }
    if (buckets.colors.length > 0) {
      const isScale = buckets.colors.every(l => /^\d+$/.test(String(l.name).trim()));
      if (isScale) buckets.colors.sort((a, b) => Number(a.name) - Number(b.name));
      sections.push({ name: groupName, leaves: buckets.colors, isScale, kind: "color" });
    }
    if (buckets.numbers.length > 0) {
      buckets.numbers.sort((a, b) => a.value - b.value);
      sections.push({ name: groupName, leaves: buckets.numbers, kind: "number" });
    }
    if (buckets.strings.length > 0 && buckets.textStyles.length === 0) {
      // Strings stand alone only when no text-styles consumed them.
      sections.push({ name: groupName, leaves: buckets.strings, kind: "string-list" });
    }
  }

  if (rootStrings.length > 0) {
    sections.push({ name: "Typography", leaves: rootStrings, kind: "typography" });
  }
  return sections;
}

function walkGroup(group, path, buckets) {
  // A text-style spec is a group whose direct children are all $value-bearing
  // leaves and include font-family or font-size. Capture it and stop descending.
  const spec = extractTextStyle(group);
  if (spec) {
    buckets.textStyles.push({
      name: path[path.length - 1] || "Style",
      slug: path.map(slugify).join("."),
      spec,
      figmaId: spec._figmaId,
      scopes: spec._scopes,
    });
    return;
  }

  for (const [k, v] of Object.entries(group)) {
    if (k.startsWith("$")) continue;
    if (!v || typeof v !== "object") continue;
    if ("$value" in v && "$type" in v) {
      const slug = [...path, k].map(slugify).join(".");
      const ext = v.$extensions || {};
      const common = {
        name: k,
        slug,
        figmaId: ext["com.figma.variableId"] || null,
        scopes: ext["com.figma.scopes"] || null,
      };
      if (v.$type === "color") {
        const hex = extractHex(v);
        if (hex) buckets.colors.push({ ...common, hex });
      } else if (v.$type === "number") {
        buckets.numbers.push({ ...common, value: v.$value });
      } else if (v.$type === "string") {
        buckets.strings.push({ ...common, value: v.$value });
      }
    } else {
      walkGroup(v, [...path, k], buckets);
    }
  }
}

function extractTextStyle(group) {
  const keys = Object.keys(group).filter(k => !k.startsWith("$"));
  if (keys.length === 0) return null;
  let hasFontFamily = false, hasFontSize = false;
  const spec = {};
  let firstExt = null;
  for (const k of keys) {
    const v = group[k];
    if (!v || typeof v !== "object") return null;
    if (!("$value" in v) || !("$type" in v)) return null;
    spec[k] = v.$value;
    if (!firstExt) firstExt = v.$extensions || {};
    const lower = k.toLowerCase();
    if (lower === "font-family") hasFontFamily = true;
    if (lower === "font-size")   hasFontSize = true;
  }
  if (!hasFontFamily && !hasFontSize) return null;
  spec._ext = firstExt;
  spec._figmaId = firstExt["com.figma.variableId"] || null;
  spec._scopes = firstExt["com.figma.scopes"] || null;
  return spec;
}

function extractHex(node) {
  const v = node.$value;
  if (typeof v === "string" && /^#[0-9a-fA-F]{6,8}$/.test(v)) return v.toUpperCase();
  if (v && typeof v === "object" && typeof v.hex === "string") return v.hex.toUpperCase();
  return null;
}

// Mirror the emitters' naming so the preview is the truth about what code sees.
function platformNames(slug) {
  return {
    android: `R.color.${snake(slug)}`,
    ios:     `BrandToken.${camel(slug)}`,
    css:     `var(--${kebab(slug)})`,
  };
}

function renderNamedSection(section) {
  const cards = section.leaves.map(leaf => {
    const fg = isDarkHex(leaf.hex) ? "#FFFFFF" : "#0F0F0F";
    const scopes = formatScopes(leaf.scopes);
    const p = leaf.platforms;
    return `
        <article class="card">
          <div class="swatch" style="background: ${leaf.hex}; color: ${fg};">${leaf.hex}</div>
          <div class="meta">
            <div class="name">${escapeHtml(leaf.name)}</div>
            <code class="slug">${leaf.slug}</code>
            <dl>
              <dt>Figma&nbsp;ID</dt><dd>${leaf.figmaId ? escapeHtml(leaf.figmaId) : "—"}</dd>
              <dt>Scopes</dt><dd>${scopes}</dd>
            </dl>
            <div class="platforms">
              <div class="row"><span class="lane">Android</span><span class="ref">${escapeHtml(p.android)}</span></div>
              <div class="row"><span class="lane">iOS</span><span class="ref">${escapeHtml(p.ios)}</span></div>
              <div class="row"><span class="lane">CSS</span><span class="ref">${escapeHtml(p.css)}</span></div>
            </div>
          </div>
        </article>`;
  }).join("");
  return `
  <section>
    <div class="section-head">
      <h2>${escapeHtml(section.name)} <span class="tier">Foundation</span></h2>
      <span class="badge">${section.leaves.length} tokens</span>
    </div>
    <div class="card-grid">${cards}
    </div>
  </section>`;
}

function renderScaleSection(section) {
  const cells = section.leaves.map(leaf => {
    const fg = isDarkHex(leaf.hex) ? "#FFFFFF" : "#0F0F0F";
    return `
        <div class="scale-cell" style="background: ${leaf.hex}; color: ${fg};">
          <span class="step">${escapeHtml(leaf.name)}</span>
          <span class="hex">${leaf.hex.replace("#", "")}</span>
        </div>`;
  }).join("");
  const rows = section.leaves.map(leaf => {
    const p = leaf.platforms;
    return `
        <tr>
          <td><span class="swatch-dot" style="background: ${leaf.hex};"></span>${escapeHtml(leaf.name)}</td>
          <td>${leaf.slug}</td>
          <td>${leaf.hex}</td>
          <td class="muted">${escapeHtml(p.android)}</td>
          <td class="muted">${escapeHtml(p.ios)}</td>
          <td class="muted">${escapeHtml(p.css)}</td>
        </tr>`;
  }).join("");
  return `
  <section>
    <div class="section-head">
      <h2>${escapeHtml(section.name)} <span class="tier">Foundation · Scale</span></h2>
      <span class="badge">${section.leaves.length} steps</span>
    </div>
    <div class="scale">${cells}
    </div>
    <table class="scale-table">
      <thead><tr><th>Step</th><th>Slug</th><th>Hex</th><th>Android</th><th>iOS</th><th>CSS</th></tr></thead>
      <tbody>${rows}
      </tbody>
    </table>
  </section>`;
}

function renderTypographySection(section) {
  // Group leaves by font-family value so the preview shows one block per
  // family with all its named variants underneath.
  const byFamily = new Map();
  for (const leaf of section.leaves) {
    const family = leaf.value;
    if (!byFamily.has(family)) byFamily.set(family, []);
    byFamily.get(family).push(leaf);
  }

  const blocks = Array.from(byFamily.entries()).map(([family, leaves]) => {
    const sample = `The quick brown fox jumps over the lazy dog`;
    const rows = leaves.map(leaf => {
      const p = leaf.platforms;
      const scopes = formatScopes(leaf.scopes);
      return `
        <tr>
          <td>${escapeHtml(leaf.name)}</td>
          <td>${leaf.slug}</td>
          <td class="muted">${leaf.figmaId ? escapeHtml(leaf.figmaId) : "—"}</td>
          <td class="muted">${scopes}</td>
          <td class="muted">${escapeHtml(p.css)}</td>
        </tr>`;
    }).join("");
    return `
    <div class="type-block">
      <div class="type-sample" style="font-family: ${cssFontStack(family)};">${sample}</div>
      <div class="type-meta">
        <code class="family">${escapeHtml(family)}</code>
        <span class="count">${leaves.length} variants</span>
      </div>
      <table class="scale-table">
        <thead><tr><th>Variant</th><th>Slug</th><th>Figma ID</th><th>Scopes</th><th>CSS</th></tr></thead>
        <tbody>${rows}
        </tbody>
      </table>
    </div>`;
  }).join("\n");

  return `
  <section>
    <div class="section-head">
      <h2>${escapeHtml(section.name)} <span class="tier">Foundation · Strings</span></h2>
      <span class="badge">${byFamily.size} ${byFamily.size === 1 ? "family" : "families"} · ${section.leaves.length} tokens</span>
    </div>
    <div class="type-grid">${blocks}
    </div>
  </section>`;
}

function cssFontStack(family) {
  const safe = String(family).replace(/['"]/g, "");
  return `'${safe}', system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif`;
}

// Radius / spacing / any "number" type — show one tile per value so the
// rounded corner (or other treatment) is legible at a glance.
function renderNumberSection(section) {
  const isRadiusLike = /radius|corner/i.test(section.name);
  const tiles = section.leaves.map(leaf => {
    const v = leaf.value;
    const treatment = isRadiusLike
      ? `border-radius: ${v}px;`
      : `width: ${Math.max(8, Math.min(120, v * 2))}px;`;
    return `
        <div class="num-tile">
          <div class="num-swatch" style="${treatment}"></div>
          <div class="num-step">${escapeHtml(leaf.name)}</div>
          <div class="num-value">${v}px</div>
        </div>`;
  }).join("");
  const rows = section.leaves.map(leaf => {
    const p = leaf.platforms;
    return `
        <tr>
          <td>${escapeHtml(leaf.name)}</td>
          <td>${leaf.slug}</td>
          <td>${leaf.value}px</td>
          <td class="muted">${escapeHtml(p.android)}</td>
          <td class="muted">${escapeHtml(p.ios)}</td>
          <td class="muted">${escapeHtml(p.css)}</td>
        </tr>`;
  }).join("");
  return `
  <section>
    <div class="section-head">
      <h2>${escapeHtml(section.name)} <span class="tier">Foundation · Numbers</span></h2>
      <span class="badge">${section.leaves.length} values</span>
    </div>
    <div class="num-grid">${tiles}
    </div>
    <table class="scale-table">
      <thead><tr><th>Step</th><th>Slug</th><th>Value</th><th>Android</th><th>iOS</th><th>CSS</th></tr></thead>
      <tbody>${rows}
      </tbody>
    </table>
  </section>`;
}

// Composed text styles — each spec ({font-family, font-weight, font-size,
// line-height, letter-spacing}) renders as a card showing the live style
// applied to a sample sentence.
function renderTextStyleSection(section) {
  const cards = section.leaves.map(leaf => {
    const s = leaf.spec;
    const family = s["font-family"] || "system";
    const size   = Number(s["font-size"]) || 16;
    const weight = mapWeight(s["font-weight"]);
    const line   = s["line-height"] !== undefined ? Number(s["line-height"]) : null;
    const track  = s["letter-spacing"] !== undefined ? Number(s["letter-spacing"]) : null;
    const stack  = cssFontStack(family);
    const styleAttr = [
      `font-family: ${stack}`,
      `font-size: ${size}px`,
      `font-weight: ${weight}`,
      line !== null ? `line-height: ${line > 4 ? line + "px" : line}` : null,
      track !== null ? `letter-spacing: ${track}px` : null,
    ].filter(Boolean).join("; ");

    const specRows = Object.entries(s)
      .filter(([k]) => !k.startsWith("_"))
      .map(([k, v]) => `<dt>${escapeHtml(k)}</dt><dd>${escapeHtml(String(v))}</dd>`)
      .join("");

    const scopes = formatScopes(leaf.scopes);
    return `
        <article class="ts-card">
          <div class="ts-sample" style="${styleAttr}">${escapeHtml(leaf.name)}</div>
          <div class="ts-meta">
            <code class="slug">${leaf.slug}</code>
            <dl class="ts-spec">${specRows}</dl>
            <dl class="ts-extra">
              <dt>Figma&nbsp;ID</dt><dd>${leaf.figmaId ? escapeHtml(leaf.figmaId) : "—"}</dd>
              <dt>Scopes</dt><dd>${scopes}</dd>
            </dl>
          </div>
        </article>`;
  }).join("");
  return `
  <section>
    <div class="section-head">
      <h2>${escapeHtml(section.name)} <span class="tier">Foundation · Text styles</span></h2>
      <span class="badge">${section.leaves.length} styles</span>
    </div>
    <div class="ts-grid">${cards}
    </div>
  </section>`;
}

// Fallback for groups of plain strings with no composed text-style structure.
function renderStringListSection(section) {
  const rows = section.leaves.map(leaf => {
    const p = leaf.platforms;
    return `
        <tr>
          <td>${escapeHtml(leaf.name)}</td>
          <td>${leaf.slug}</td>
          <td>${escapeHtml(leaf.value)}</td>
          <td class="muted">${escapeHtml(p.css)}</td>
        </tr>`;
  }).join("");
  return `
  <section>
    <div class="section-head">
      <h2>${escapeHtml(section.name)} <span class="tier">Foundation · Strings</span></h2>
      <span class="badge">${section.leaves.length} tokens</span>
    </div>
    <table class="scale-table">
      <thead><tr><th>Name</th><th>Slug</th><th>Value</th><th>CSS</th></tr></thead>
      <tbody>${rows}
      </tbody>
    </table>
  </section>`;
}

// Figma exports font-weight as words ("Bold", "Medium"); map to numeric so
// CSS picks up an accurate weight even when the named family doesn't load.
function mapWeight(w) {
  if (typeof w === "number") return w;
  const norm = String(w || "").toLowerCase().replace(/[\s-]/g, "");
  if (norm.includes("thin")) return 100;
  if (norm.includes("extralight") || norm.includes("ultralight")) return 200;
  if (norm.includes("light")) return 300;
  if (norm.includes("regular") || norm === "normal" || norm === "") return 400;
  if (norm.includes("medium")) return 500;
  if (norm.includes("semibold") || norm.includes("demibold")) return 600;
  if (norm.includes("extrabold") || norm.includes("ultrabold")) return 800;
  if (norm.includes("black") || norm.includes("heavy")) return 900;
  if (norm.includes("bold")) return 700;
  return 400;
}

function formatScopes(scopes) {
  if (!Array.isArray(scopes) || scopes.length === 0) return "—";
  return scopes.map(escapeHtml).join(", ");
}

function isDarkHex(hex) {
  if (!hex || typeof hex !== "string") return true;
  const m = hex.replace("#", "");
  if (m.length < 6) return true;
  const r = parseInt(m.slice(0, 2), 16) / 255;
  const g = parseInt(m.slice(2, 4), 16) / 255;
  const b = parseInt(m.slice(4, 6), 16) / 255;
  const lin = c => c <= 0.03928 ? c / 12.92 : Math.pow((c + 0.055) / 1.055, 2.4);
  const L = 0.2126 * lin(r) + 0.7152 * lin(g) + 0.0722 * lin(b);
  return L < 0.55;
}

function escapeHtml(s) {
  return String(s)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

// -- I/O ---------------------------------------------------------------------

function writeFile(path, contents) {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, contents);
}
